# -*- coding: utf-8 -*-
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# General configuration

# Add any Sphinx extension module names here, as strings.
extensions = ['sphinx.ext.autodoc', "sphinx.ext.mathjax", 'sphinx_copybutton']

# The suffix(es) of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'PangyPlot'
copyright = u'2025, Scott Mastromatteo'
author = u'Scott Mastromatteo'

# The version info for the project you're documenting.
version = u'1.0.0'
release = u'1.0.0'

# The language for content autogenerated by Sphinx.
language = 'en'

# List of patterns, relative to source directory, to ignore when looking for source files.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# Options for HTML output

# The theme to use for HTML and HTML Help pages.
html_theme = "sphinx_rtd_theme"

# Add any paths that contain custom static files (such as style sheets) here, relative to this directory.
# Ensure these directories exist or comment out if not used.
html_static_path = ['_static']

# Custom sidebar templates.
html_sidebars = {
    '**': [
        'relations.html', 
        'searchbox.html',
    ]
}

html_css_files = [
    'pangyplot.css',
    'font.css',
    'screenshot.css',
    'fontawesome/css/all.css',
]

html_js_files = [
    'screenshot.js',
]


myst_enable_extensions = ["html_admonition", "html_image"]

# HTMLHelp output.
htmlhelp_basename = 'pangyplotdocs'

# LaTeX output.
latex_documents = [
    (master_doc, 'pangyplot.tex', u'PangyPlot Documentation',
     u'Scott Mastromatteo', 'manual'),
]

# Manual page output.
man_pages = [
    (master_doc, 'pangyplot', u'PangyPlot Documentation',
     [author], 1)
]

# Texinfo output.
texinfo_documents = [
    (master_doc, 'pangyplot', u'PangyPlot Documentation',
     author, 'pangyplot', 'Visualizing pangenomes.',
     'Miscellaneous'),
]

# Path to logo and favicon. Ensure these files exist at the specified paths.
html_logo = "_images/logo/pangyplot.svg"
html_favicon = "_images/icon/favicon_black.svg"

